### ISSUE TITLE
fantastic reality dataset

### ISSUE THREAD

**Issue by CIawevy** [greatzh/Image-Forgery-Datasets-List#1]
Hi, thanks for your help for collecting dataset information and offering us useful link to collect dataset.
I just wondering how to fetch the dataset named Fantastic Reality ，since I have written 5 emails in 3 months to the author ,with no response..

**Comment by greatzh** [comment]
I apologize for the delay. I checked my email, and it looks like I also reached out to the author already, but haven't heard back yet. So, I don't have any more information to give you right now. However, I know there are some papers* in recent two years out there that have used this dataset in their experiments. Maybe they can help you get your hands on it.

1. [The Point Where Reality Meets Fantasy: Mixed Adversarial Generators for Image Splice Detection](https://proceedings.neurips.cc/paper_files/paper/2019/hash/98dce83da57b0395e163467c9dae521b-Abstract.html)
2. [Multi-Task Wavelet Corrected Network for Image Splicing Forgery Detection and Localization](https://ieeexplore.ieee.org/document/9428466)
3. [Reality Transform Adversarial Generators for Image Splicing Forgery Detection
and Localization](https://openaccess.thecvf.com/content/ICCV2021/papers/Bi_Reality_Transform_Adversarial_Generators_for_Image_Splicing_Forgery_Detection_and_ICCV_2021_paper.pdf)
4. [CAT-Net: Compression Artifact Tracing Network for Detection and Localization
of Image Splicing](https://openaccess.thecvf.com/content/WACV2021/papers/Kwon_CAT-Net_Compression_Artifact_Tracing_Network_for_Detection_and_Localization_of_WACV_2021_paper.pdf)
5. [Learning to localize image forgery using end-to-end attention network](https://www.sciencedirect.com/science/article/abs/pii/S0925231222011274)

**Comment by CIawevy** [comment]
Many thanks

**Comment by bfhdndh** [comment]
> 您好，感谢您帮助收集数据集信息并为我们提供有用的链接来收集数据集。我只是在想如何获取名为Fantastic Reality的数据集，因为我在3个月内给作者写了5封电子邮件，但没有回复..

你好，请问你找到这个数据集了吗？
